-- Genera comandos para copiar TODAS las tablas del share

SELECT 'CREATE TABLE ADVENTURE_WORKS.' || TABLE_SCHEMA || '.' || TABLE_NAME || ' AS SELECT * FROM ADVENTURE_WORKS_1.' || TABLE_SCHEMA || '.' || TABLE_NAME || ';'
FROM ADVENTURE_WORKS_1.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- Crear BD
CREATE DATABASE ADVENTURE_WORKS;

-- Crear esquemas
CREATE SCHEMA ADVENTURE_WORKS.HUMAN_RESOURCES;
CREATE SCHEMA ADVENTURE_WORKS.PERSON;
CREATE SCHEMA ADVENTURE_WORKS.PRODUCTION;
CREATE SCHEMA ADVENTURE_WORKS.PURCHASING;
CREATE SCHEMA ADVENTURE_WORKS.SALES;

CREATE TABLE ADVENTURE_WORKS.HUMAN_RESOURCES.DEPARTMENT AS SELECT * FROM ADVENTURE_WORKS_1.HUMAN_RESOURCES.DEPARTMENT;
CREATE TABLE ADVENTURE_WORKS.HUMAN_RESOURCES.EMPLOYEE AS SELECT * FROM ADVENTURE_WORKS_1.HUMAN_RESOURCES.EMPLOYEE;
CREATE TABLE ADVENTURE_WORKS.HUMAN_RESOURCES.EMPLOYEE_DEPARTMENT_HISTORY AS SELECT * FROM ADVENTURE_WORKS_1.HUMAN_RESOURCES.EMPLOYEE_DEPARTMENT_HISTORY;
CREATE TABLE ADVENTURE_WORKS.HUMAN_RESOURCES.EMPLOYEE_PAY_HISTORY AS SELECT * FROM ADVENTURE_WORKS_1.HUMAN_RESOURCES.EMPLOYEE_PAY_HISTORY;
CREATE TABLE ADVENTURE_WORKS.HUMAN_RESOURCES.JOB_CANDIDATE AS SELECT * FROM ADVENTURE_WORKS_1.HUMAN_RESOURCES.JOB_CANDIDATE;
CREATE TABLE ADVENTURE_WORKS.HUMAN_RESOURCES.SHIFT AS SELECT * FROM ADVENTURE_WORKS_1.HUMAN_RESOURCES.SHIFT;
CREATE TABLE ADVENTURE_WORKS.PERSON.ADDRESS AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.ADDRESS;
CREATE TABLE ADVENTURE_WORKS.PERSON.ADDRESS_TYPE AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.ADDRESS_TYPE;
CREATE TABLE ADVENTURE_WORKS.PERSON.BUSINESS_ENTITY AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.BUSINESS_ENTITY;
CREATE TABLE ADVENTURE_WORKS.PERSON.BUSINESS_ENTITY_ADDRESS AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.BUSINESS_ENTITY_ADDRESS;
CREATE TABLE ADVENTURE_WORKS.PERSON.BUSINESS_ENTITY_CONTACT AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.BUSINESS_ENTITY_CONTACT;
CREATE TABLE ADVENTURE_WORKS.PERSON.CONTACT_TYPE AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.CONTACT_TYPE;
CREATE TABLE ADVENTURE_WORKS.PERSON.COUNTRY_REGION AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.COUNTRY_REGION;
CREATE TABLE ADVENTURE_WORKS.PERSON.EMAIL_ADDRESS AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.EMAIL_ADDRESS;
CREATE TABLE ADVENTURE_WORKS.PERSON.PASSWORD AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.PASSWORD;
CREATE TABLE ADVENTURE_WORKS.PERSON.PERSON AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.PERSON;
CREATE TABLE ADVENTURE_WORKS.PERSON.PERSON_PHONE AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.PERSON_PHONE;
CREATE TABLE ADVENTURE_WORKS.PERSON.STATE_PROVINCE AS SELECT * FROM ADVENTURE_WORKS_1.PERSON.STATE_PROVINCE;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.BILL_OF_MATERIALS AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.BILL_OF_MATERIALS;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.CULTURE AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.CULTURE;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.LOCATION AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.LOCATION;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.PRODUCT AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.PRODUCT;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.PRODUCT_CATEGORY AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.PRODUCT_CATEGORY;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.PRODUCT_COST_HISTORY AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.PRODUCT_COST_HISTORY;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.PRODUCT_DESCRIPTION AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.PRODUCT_DESCRIPTION;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.PRODUCT_INVENTORY AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.PRODUCT_INVENTORY;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.PRODUCT_SUBCATEGORY AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.PRODUCT_SUBCATEGORY;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.TRANSACTION_HISTORY AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.TRANSACTION_HISTORY;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.UNIT_MEASURE AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.UNIT_MEASURE;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.WORK_ORDER AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.WORK_ORDER;
CREATE TABLE ADVENTURE_WORKS.PRODUCTION.WORK_ORDER_ROUTING AS SELECT * FROM ADVENTURE_WORKS_1.PRODUCTION.WORK_ORDER_ROUTING;
CREATE TABLE ADVENTURE_WORKS.PURCHASING.PRODUCT_VENDOR AS SELECT * FROM ADVENTURE_WORKS_1.PURCHASING.PRODUCT_VENDOR;
CREATE TABLE ADVENTURE_WORKS.PURCHASING.PURCHASE_ORDER_DETAIL AS SELECT * FROM ADVENTURE_WORKS_1.PURCHASING.PURCHASE_ORDER_DETAIL;
CREATE TABLE ADVENTURE_WORKS.PURCHASING.PURCHASE_ORDER_HEADER AS SELECT * FROM ADVENTURE_WORKS_1.PURCHASING.PURCHASE_ORDER_HEADER;
CREATE TABLE ADVENTURE_WORKS.PURCHASING.SHIP_METHOD AS SELECT * FROM ADVENTURE_WORKS_1.PURCHASING.SHIP_METHOD;
CREATE TABLE ADVENTURE_WORKS.PURCHASING.VENDOR AS SELECT * FROM ADVENTURE_WORKS_1.PURCHASING.VENDOR;
CREATE TABLE ADVENTURE_WORKS.SALES.COLLISION_TRACKER AS SELECT * FROM ADVENTURE_WORKS_1.SALES.COLLISION_TRACKER;
CREATE TABLE ADVENTURE_WORKS.SALES.COUNTRY_REGION_CURRENCY AS SELECT * FROM ADVENTURE_WORKS_1.SALES.COUNTRY_REGION_CURRENCY;
CREATE TABLE ADVENTURE_WORKS.SALES.CREDIT_CARD AS SELECT * FROM ADVENTURE_WORKS_1.SALES.CREDIT_CARD;
CREATE TABLE ADVENTURE_WORKS.SALES.CURRENCY AS SELECT * FROM ADVENTURE_WORKS_1.SALES.CURRENCY;
CREATE TABLE ADVENTURE_WORKS.SALES.CURRENCY_RATE AS SELECT * FROM ADVENTURE_WORKS_1.SALES.CURRENCY_RATE;
CREATE TABLE ADVENTURE_WORKS.SALES.CUSTOMER AS SELECT * FROM ADVENTURE_WORKS_1.SALES.CUSTOMER;
CREATE TABLE ADVENTURE_WORKS.SALES.INJURY_TRACKER AS SELECT * FROM ADVENTURE_WORKS_1.SALES.INJURY_TRACKER;
CREATE TABLE ADVENTURE_WORKS.SALES.PERSON_CREDIT_CARD AS SELECT * FROM ADVENTURE_WORKS_1.SALES.PERSON_CREDIT_CARD;
CREATE TABLE ADVENTURE_WORKS.SALES.SALES_ORDER_DETAIL AS SELECT * FROM ADVENTURE_WORKS_1.SALES.SALES_ORDER_DETAIL;
CREATE TABLE ADVENTURE_WORKS.SALES.SALES_ORDER_HEADER AS SELECT * FROM ADVENTURE_WORKS_1.SALES.SALES_ORDER_HEADER;
CREATE TABLE ADVENTURE_WORKS.SALES.SALES_ORDER_HEADER_SALES_REASON AS SELECT * FROM ADVENTURE_WORKS_1.SALES.SALES_ORDER_HEADER_SALES_REASON;
CREATE TABLE ADVENTURE_WORKS.SALES.SALES_PERSON AS SELECT * FROM ADVENTURE_WORKS_1.SALES.SALES_PERSON;
CREATE TABLE ADVENTURE_WORKS.SALES.SALES_TAX_RATE AS SELECT * FROM ADVENTURE_WORKS_1.SALES.SALES_TAX_RATE;
CREATE TABLE ADVENTURE_WORKS.SALES.SALES_TERRITORY AS SELECT * FROM ADVENTURE_WORKS_1.SALES.SALES_TERRITORY;
CREATE TABLE ADVENTURE_WORKS.SALES.SALES_TERRITORY_HISTORY AS SELECT * FROM ADVENTURE_WORKS_1.SALES.SALES_TERRITORY_HISTORY;
CREATE TABLE ADVENTURE_WORKS.SALES.SHOPPING_CART_ITEM AS SELECT * FROM ADVENTURE_WORKS_1.SALES.SHOPPING_CART_ITEM;
CREATE TABLE ADVENTURE_WORKS.SALES.SPECIAL_OFFER AS SELECT * FROM ADVENTURE_WORKS_1.SALES.SPECIAL_OFFER;
CREATE TABLE ADVENTURE_WORKS.SALES.SPECIAL_OFFER_PRODUCT AS SELECT * FROM ADVENTURE_WORKS_1.SALES.SPECIAL_OFFER_PRODUCT;
CREATE TABLE ADVENTURE_WORKS.SALES.STORE AS SELECT * FROM ADVENTURE_WORKS_1.SALES.STORE;

CREATE OR REPLACE TABLE  ADVENTURE_WORKS.SALES.SALES_REASON(
SalesReasonID NUMBER, Name VARCHAR(30), ReasonType  VARCHAR(20),ModifiedDate VARCHAR(20)
);
INSERT INTO ADVENTURE_WORKS.SALES.SALES_REASON VALUES
(1,'Price','Other','2026-09-23'),
(2,'On Promotion','Promotion','2026-09-23'),
(3,'Magazine Advertisement','Marketing', '2026-09-23'),
(4,'Television  Advertisement','Marketing', '2026-09-23'),
(5,'Manufacturer','Other', '2026-09-23'),
(6,'Review','Other', '2026-09-23'),
(7,'Demo Event','Marketing', '2026-09-23'),
(8,'Sponsorship','Marketing', '2026-09-23'),
(9,'Quality','Other', '2026-09-23'),
(10,'Other','Other', '2026-09-23');


USE ROLE ACCOUNTADMIN;
DROP DATABASE ADVENTURE_WORKS_1;