CREATE OR REPLACE DATABASE ADW_BRONZE_DEV;
CREATE OR REPLACE DATABASE ADW_SILVER_DEV;
CREATE OR REPLACE DATABASE ADW_GOLD_DEV;
CREATE OR REPLACE DATABASE ADW_PLATINUM_DEV;

CREATE OR REPLACE DATABASE ADW_BRONZE_UAT;
CREATE OR REPLACE DATABASE ADW_SILVER_UAT;
CREATE OR REPLACE DATABASE ADW_GOLD_UAT;
CREATE OR REPLACE DATABASE ADW_PLATINUM_UAT;

CREATE OR REPLACE DATABASE ADW_BRONZE_PRD;
CREATE OR REPLACE DATABASE ADW_SILVER_PRD;
CREATE OR REPLACE DATABASE ADW_GOLD_PRD;
CREATE OR REPLACE DATABASE ADW_PLATINUM_PRD;
CREATE DATABASE 'PUBLIC';

