CREATE TEMPORARY TABLE SALES_ORDER_H AS
SELECT SALES_ORDER_ID, DUE_DATE, ORDER_DATE, SHIP_DATE,
       DATEDIFF(day, ORDER_DATE::DATE, DUE_DATE::DATE)  AS DUE_GAP,
       DATEDIFF(day, ORDER_DATE::DATE, SHIP_DATE::DATE) AS SHIP_GAP
FROM ADVENTURE_WORKS.SALES.SALES_ORDER_HEADER;

-- Step 1: Calculate the upper bound days
SET MAX_DAYS = (
    SELECT DATEDIFF(
        day, 
        '2026-01-01'::date, 
        DATEADD(day, - MAX(DUE_GAP), CURRENT_DATE())
    ) 
    FROM SALES_ORDER_H
);

-- Step 2: Use the session variable inside UNIFORM
UPDATE SALES_ORDER_H     
SET ORDER_DATE = TO_VARCHAR(
    DATEADD(
        day,      
        UNIFORM(0, $MAX_DAYS, RANDOM()),     
        '2026-01-01'::date
    ), 
    'YYYY-MM-DD'
);

UPDATE SALES_ORDER_H
SET DUE_DATE  = TO_VARCHAR(DATEADD(day, DUE_GAP, ORDER_DATE::DATE), 'YYYY-MM-DD'),
    SHIP_DATE = TO_VARCHAR(DATEADD(day, SHIP_GAP, ORDER_DATE::DATE), 'YYYY-MM-DD');

SELECT ORDER_DATE, COUNT(*) FROM SALES_ORDER_H GROUP BY ORDER_DATE;

UPDATE ADVENTURE_WORKS.SALES.SALES_ORDER_HEADER AS t1
    SET t1.ORDER_DATE = t2.ORDER_DATE,
    t1.DUE_DATE = t2.DUE_DATE,
    t1.SHIP_DATE = t2.SHIP_DATE
FROM SALES_ORDER_H AS t2
WHERE t1.SALES_ORDER_ID = t2.SALES_ORDER_ID;

DECLARE
    cols CURSOR FOR
        SELECT c.TABLE_CATALOG, c.TABLE_SCHEMA, c.TABLE_NAME,
               CASE c.DATA_TYPE
                   WHEN 'TEXT' THEN 'TO_CHAR(CURRENT_DATE(), ''YYYY-MM-DD'')'
                   WHEN 'DATE' THEN 'CURRENT_DATE()'
                   ELSE 'CURRENT_TIMESTAMP()'
               END AS VALOR
        FROM ADVENTURE_WORKS.INFORMATION_SCHEMA.COLUMNS c
        JOIN ADVENTURE_WORKS.INFORMATION_SCHEMA.TABLES t
          ON t.TABLE_SCHEMA = c.TABLE_SCHEMA
         AND t.TABLE_NAME   = c.TABLE_NAME
         AND t.TABLE_TYPE   = 'BASE TABLE'
        WHERE c.COLUMN_NAME = 'MODIFIED_DATE';
    n INTEGER DEFAULT 0;
BEGIN
    FOR col IN cols DO
        EXECUTE IMMEDIATE
            'UPDATE "' || col.TABLE_CATALOG || '"."' || col.TABLE_SCHEMA || '"."'
            || col.TABLE_NAME || '" SET "MODIFIED_DATE" = ' || col.VALOR;
        n := n + 1;
    END FOR;
    RETURN n || ' tablas actualizadas';
END;

SELECT c.TABLE_CATALOG, c.TABLE_SCHEMA, c.TABLE_NAME, c.COLUMN_NAME, c.DATA_TYPE
        FROM ADVENTURE_WORKS.INFORMATION_SCHEMA.COLUMNS c
        JOIN ADVENTURE_WORKS.INFORMATION_SCHEMA.TABLES t
          ON t.TABLE_SCHEMA = c.TABLE_SCHEMA
         AND t.TABLE_NAME = c.TABLE_NAME
         AND t.TABLE_TYPE = 'BASE TABLE'
        WHERE c.TABLE_SCHEMA <> 'INFORMATION_SCHEMA' AND c.COLUMN_NAME = 'MODIFIED_DATE'
        ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME, c.ORDINAL_POSITION;